slam_toolbox:
  ros__parameters:
    use_sim_time: false
    slam_mode: "mapping"
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_footprint"
    scan_topic: "/scan"
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.05
    transform_timeout: 0.3
    tf_buffer_duration: 15.0
    map_update_interval: 2.0
